server:
  port: 8100

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: CURRENCY-CONVERSION-SERVICE

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

currency-exchange-base-path:
  url: http://localhost:8001

resilience4j:
  retry:
    instances:
      exchange:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: false
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 10s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
