
server:
  port: ${PORT:88}

spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URL}
          clone-on-start: true
#          uri: file:///Users/nazel/Documents/devTraining/microservice-appDemo/MicroService-dev/local-git-cofig

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
